apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "shi-model-pvc"
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  predictor:
    sklearn:
      storageUri: "pvc://task-pv-claim/model.bst"