apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "shi-model-pvc"
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  predictor:
    containers:
      - name: kserve-container
        imagePullPolicy: Never
        image: docker.io/ruivieira/rhods-shi-model:latest